# Generated by Django 3.2.9 on 2021-12-07 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_records_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_revenue', models.DecimalField(decimal_places=2, default=100.89, max_digits=6, verbose_name='Total Revenue')),
                ('Total_buyers_invovlved', models.PositiveIntegerField(default=13, verbose_name='Total Buyers Involved')),
                ('Total_sellers_involved', models.PositiveIntegerField(default=89, verbose_name='Total Sellers Involved')),
                ('Total_collectors_involved', models.PositiveIntegerField(default=8, verbose_name='Totak Collectors Involved')),
                ('Total_transporters_involved', models.PositiveIntegerField(default=2, verbose_name='Total Transporters Involved')),
                ('Total_users_involved', models.PositiveIntegerField(default=112, verbose_name='Total users Involved')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_records_individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sales_value')),
                ('date_involved', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('ordered_date', models.DateTimeField(auto_now_add=True, verbose_name='Ordered Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('Is_collected_with_collecter', models.BooleanField(verbose_name='is collected with collecter')),
                ('Is_transported_With_Transporter', models.BooleanField(verbose_name='is trasported with traspoter')),
                ('Collecter_precentage', models.PositiveIntegerField(default=0.02, verbose_name='Collecter Precentages')),
                ('Transpoter_Tip', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Transpoter Tip')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
